### ISSUE TITLE
elementUI 多选框 after 样式问题

### ISSUE THREAD

**Issue by Leopold1988** [Power-kxLee/vue3-print-nb#4]
vue3-print-nb@0.1.4
element-plus@2.2.17

以下是打印预览看到的问题样式，el-checkbox 组件的 `border-right` 和 `border-bottom` 样式丢失，导致看不到选中的对勾。
```css
.el-checkbox__inner::after {
    box-sizing: content-box;
    content: "";
    border-right-color: ;
    border-right-style: ;
    border-right-width: ;
    border-bottom-color: ;
    border-bottom-style: ;
    border-bottom-width: ;
    border-image-source: ;
    border-image-slice: ;
    border-image-width: ;
    border-image-outset: ;
    border-image-repeat: ;
    border-left: 0px;
    border-top: 0px;
    height: 7px;
    left: 4px;
    position: absolute;
    top: 1px;
    transform: rotate(45deg) scaleY(0);
    width: 3px;
    transition: transform 0.15s ease-in 50ms;
    transform-origin: center center;
}
```
